export const CHANGE_BLOG_UI = 'CHANGE_BLOG_UI'
export const CHANGE_BLOG_DOMAIN = 'CHANGE_BLOG_DOMAIN'
export const SELECT_BLOG = 'SELECT_BLOG'
export const SELECT_BLOG_SUCCESS = 'SELECT_BLOG_SUCCESS'
export const SELECT_BLOG_ERROR = 'SELECT_BLOG_ERROR'

// blog-comment
export const CREATE_BLOG_COMMENT = 'CREATE_BLOG_COMMENT'
export const CREATE_BLOG_COMMENT_SUCCESS = 'CREATE_BLOG_COMMENT_SUCCESS'
export const CREATE_BLOG_COMMENT_ERROR = 'CREATE_BLOG_COMMENT_ERROR'
export const UPDATE_BLOG_COMMENT = 'UPDATE_BLOG_COMMENT'
export const UPDATE_BLOG_COMMENT_SUCCESS = 'UPDATE_BLOG_COMMENT_SUCCESS'
export const UPDATE_BLOG_COMMENT_ERROR = 'UPDATE_BLOG_COMMENT_ERROR'
export const DELETE_BLOG_COMMENT = 'DELETE_BLOG_COMMENT'
export const DELETE_BLOG_COMMENT_SUCCESS = 'DELETE_BLOG_COMMENT_SUCCESS'
export const DELETE_BLOG_COMMENT_ERROR = 'DELETE_BLOG_COMMENT_ERROR'

// blog-comment-comment
export const CREATE_BLOG_COMMENT_COMMENT = 'CREATE_BLOG_COMMENT_COMMENT'
export const CREATE_BLOG_COMMENT_COMMENT_SUCCESS =
  'CREATE_BLOG_COMMENT_COMMENT_SUCCESS'
export const CREATE_BLOG_COMMENT_COMMENT_ERROR =
  'CREATE_BLOG_COMMENT_COMMENT_ERROR'
export const UPDATE_BLOG_COMMENT_COMMENT = 'UPDATE_BLOG_COMMENT_COMMENT'
export const UPDATE_BLOG_COMMENT_COMMENT_SUCCESS =
  'UPDATE_BLOG_COMMENT_COMMENT_SUCCESS'
export const UPDATE_BLOG_COMMENT_COMMENT_ERROR =
  'UPDATE_BLOG_COMMENT_COMMENT_ERROR'
export const DELETE_BLOG_COMMENT_COMMENT = 'DELETE_BLOG_COMMENT_COMMENT'
export const DELETE_BLOG_COMMENT_COMMENT_SUCCESS =
  'DELETE_BLOG_COMMENT_COMMENT_SUCCESS'
export const DELETE_BLOG_COMMENT_COMMENT_ERROR =
  'DELETE_BLOG_COMMENT_COMMENT_ERROR'

export const INITIAL_BLOG_OTHER_DATA_STATE = 'INITIAL_BLOG_OTHER_DATA_STATE'
export const INITIAL_BLOG_STATE = 'INITIAL_BLOG_STATE'
