export { default as MyPage } from './my-page'
export { default as MainPage } from './main-page'
export { default as BlogPage } from './blog-page'
export { default as BlogFormPage } from './blog-form-page'
export { default as MyBlogPage } from './my-blog-page'
