export { default as MyPage } from './my-page'
export { default as MainPage } from './main-page'
export { default as BlogPage } from './blog-page'
export { default as CreateBlogPage } from './create-blog-page'
export { default as UpdateBlogPage } from './update-blog-page'
export { default as MyBlogPage } from './my-blog-page'
